apiVersion: apps/v1
kind: Deployment
metadata:
  name: samasa-cluster
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: samasa
          image: danceladus/samasa
          ports:
            - containerPort: 80