Description: >
  Samasa / CloudFormation script for basic infrastructure setup

Parameters:
  EnvironmentName:
    Description: Prefix to identify connected resources
    Type: String

  VpcCIDR:
    Description: IP address range for VPC
    Type: String
  
  PublicSubnet1CIDR:
    Description: IP address range for public subnet 1
    Type: String
  
  PublicSubnet2CIDR:
    Description: IP address range for public subnet 1
    Type: String

  PrivateSubnet1CIDR:
    Description: IP address range for public subnet 1
    Type: String
  
  PrivateSubnet2CIDR:
    Description: IP address range for public subnet 1
    Type: String


Resources:

  # - -
  # VPC
  # - -
  SamasaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-VPC

  # - -
  # Internet Gateway
  # - -
  SamasaInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-InternetGateway
  SamasaInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref SamasaVPC
      InternetGatewayId: !Ref SamasaInternetGateway

  # - -
  # Subnets
  # - -

  # Public
  SamasaPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref SamasaVPC
      CidrBlock: !Ref PublicSubnet1CIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Pub1
  
  SamasaPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref SamasaVPC
      CidrBlock: !Ref PublicSubnet2CIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Pub2

  # Private
  SamasaPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref SamasaVPC
      CidrBlock: !Ref PrivateSubnet1CIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Pri1

  SamasaPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref SamasaVPC
      CidrBlock: !Ref PrivateSubnet2CIDR
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Pri2

  # - -
  # NAT Gateways
  # - -
  
  # EIPs
  SamasaNat1EIP:
    Type: AWS::EC2::EIP
    DependsOn: SamasaInternetGateway
    Properties:
      Domain: vpc
  
  SamasaNat2EIP:
    Type: AWS::EC2::EIP
    DependsOn: SamasaInternetGateway
    Properties:
      Domain: vpc

  # NAT Gateways
  SamasaNat1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt SamasaNat1EIP.AllocationId
      SubnetId: !Ref SamasaPublicSubnet1
  
  SamasaNat2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt SamasaNat2EIP.AllocationId
      SubnetId: !Ref SamasaPublicSubnet2
  