apiVersion: apps/v1
kind: Deployment
metadata:
  name: samasa-cluster
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samasa-cluster
  template:
    metadata:
      labels:
        app: samasa-cluster
    spec:
      containers:
        - name: samasa
          image: danceladus/samasa
          ports:
            - name: samasa-port
              containerPort: 80