apiVersion: v1
kind: ReplicationController
metadata:
  name: samasa-green
  labels:
    app: samasa-green
spec:
  replicas: 1
  selector:
    app: samasa-green
  template:
    metadata:
      labels:
        app: samasa-green
    spec:
      containers:
      - name: samasa-green
        image: danceladus/samasa
        ports:
        - containerPort: 80